### ISSUE TITLE
Upgrade go version to 1.16

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tipocket#412]
## Work items

- [x] Change the go version on every case
- [x]  Update the scaffolding tool
- [x]  Update the baseimage on Dockerfile
- [x]  Update CI workflow scripts
